 - name: check if disabled cronjobs exist
   command: mv {{ item }} {{ item | regex_replace('.disabled$', '') }}
   register: cronjob_disabled_results
   with_fileglob:
     - /etc/cron.daily/*.disabled
     - /etc/cron.weekly/*.disabled
     - /etc/cron.monthly/*.disabled
   when: > 
        item|regex_replace('.+/(.+).disabled', '\\1') in cronjob_enable_list and
        item|regex_replace('.+/(.+).disabled', '\\1') not in cronjob_enable_blacklist
