 - name: check if disabled cronjobs exist
   command: mv {{ item }} {{ item | regex_replace('.disabled$', '') }}
   register: cronjob_disabled_results
   with_fileglob:
     - /etc/cron.daily/*.disabled
     - /etc/cron.weekly/*.disabled
     - /etc/cron.monthly/*.disabled
   when: > 
        item|regex_replace('.+/(.+).disabled', '\\1') in ['apt', 'man-db', 'aptitude', 'bsdmainutils', 
                                                           'cracklib-runtime', 'dpkg', 'mlocate', 'passwd',
                                                            'quota', 'upstart', 'fstrim', 'logrotate'] and
        item|regex_replace('.+/(.+).disabled', '\\1') not in cronjob_enable_blacklist
